### ISSUE TITLE
Engine unlock missing in SpriteRemoveExample?

### ISSUE THREAD

**Issue by efung** [nicolasgramlich/AndEngineExamples#9]
On Line 108 of SpriteRemoveExample ( https://github.com/nicolasgramlich/AndEngineExamples/blob/GLES2/src/org/andengine/examples/SpriteRemoveExample.java#L108 ), shouldn't that be engine.unlock()?

**Comment by nicolasgramlich** [comment]
Thanks! 3e109075b1b5e8757ebc8ed427374f85bcfadbfe
